[package]
name = "simple-pastebin"
version = "0.1.1"
edition = "2021"

[dependencies]
warp = "0.3"
tokio = { version = "1.0", features = ["full", "sync"] }
serde = { version = "1.0", features = ["derive"] }
async-stream = "0.3"
